export const themes = {
  luxury: {
    name: "luxury",
    label: "Luxury",
    colors: {
      background: "#0c0b0a",
      foreground: "#f5f0e8",
      accent: "#c9a55c",
      accentLight: "#e2c992",
      accentMuted: "#8a7348",
      surface: "#161412",
      surfaceAlt: "#1f1c19",
      surfaceDark: "#0a0908",
      card: "#1a1816",
      cardBorder: "rgba(201, 165, 92, 0.35)",
      muted: "#a39e96",
      mutedOnDark: "#c4bdb3",
      mutedSubtle: "#7a746c",
      mutedBorder: "rgba(201, 165, 92, 0.15)",
      navBackground: "rgba(10, 9, 8, 0.96)",
      navBorder: "rgba(201, 165, 92, 0.3)",
      navText: "#f5f0e8",
      navLink: "rgba(245, 240, 232, 0.75)",
      heroOverlay:
        "linear-gradient(180deg, rgba(10,9,8,0.55) 0%, rgba(10,9,8,0.82) 55%, rgba(10,9,8,0.95) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(10,9,8,0.75) 0%, rgba(26,24,22,0.88) 100%)",
      bodyPattern: "none",
      sectionRoomsBg: "#161412",
      sectionAmenitiesBg: "#0a0908",
      sectionGalleryBg: "#12100e",
      sectionAltBg: "#1a1816",
      sectionBookBg: "#0a0908",
      footerBg: "#080706",
      footerBorder: "rgba(201, 165, 92, 0.2)",
      btnPrimaryBg: "#c9a55c",
      btnPrimaryText: "#0c0b0a",
      btnPrimaryHover: "#e2c992",
      btnOutlineBorder: "rgba(201, 165, 92, 0.6)",
      btnOutlineText: "#f5f0e8",
      headingOnSurface: "#f5f0e8",
      headingOnDark: "#f5f0e8",
      eyebrowColor: "#c9a55c",
    },
    fonts: {
      sans: "var(--font-lato)",
      serif: "var(--font-playfair)",
      headingWeight: "400",
      headingStyle: "normal",
      headingTransform: "uppercase",
      bodyWeight: "300",
    },
    layout: {
      sectionPaddingY: "7rem",
      sectionPaddingYLg: "9rem",
      sectionGap: "2.5rem",
      containerMax: "80rem",
      heroMinHeight: "100vh",
      navHeight: "4.5rem",
      cardPadding: "1.75rem",
    },
    buttons: {
      radius: "0px",
      paddingX: "2.25rem",
      paddingY: "0.95rem",
      tracking: "0.22em",
      fontSize: "0.7rem",
      borderWidth: "1px",
      shadow: "none",
      primaryStyle: "solid",
    },
    cards: {
      radius: "0px",
      borderWidth: "1px",
      border: "1px solid rgba(201, 165, 92, 0.25)",
      shadow: "none",
      shadowHover: "0 0 0 1px rgba(201, 165, 92, 0.5)",
      imageRadius: "0px",
    },
    images: {
      filter: "saturate(0.85) contrast(1.05) brightness(0.9)",
      hoverFilter: "saturate(0.95) contrast(1.08) brightness(0.95)",
      overlayBlend: "multiply",
    },
    navigation: {
      style: "dark-solid",
      blur: "0px",
      logoTracking: "0.35em",
      linkTracking: "0.12em",
      borderBottom: true,
    },
    headings: {
      tracking: "0.08em",
      leading: "1.15",
      h1Size: "clamp(2.75rem, 6vw, 5.5rem)",
      h2Size: "clamp(2rem, 4vw, 3.25rem)",
      eyebrowTracking: "0.35em",
    },
  },

  coastal: {
    name: "coastal",
    label: "Coastal",
    colors: {
      background: "#e8f4fa",
      foreground: "#0c3a53",
      accent: "#0077b6",
      accentLight: "#48cae4",
      accentMuted: "#90e0ef",
      surface: "#f7fcff",
      surfaceAlt: "#dff0f7",
      surfaceDark: "#023e8a",
      card: "#ffffff",
      cardBorder: "rgba(0, 119, 182, 0.12)",
      muted: "#4a7a94",
      mutedOnDark: "#caf0f8",
      mutedSubtle: "#6b9ab5",
      mutedBorder: "#bde0fe",
      navBackground: "rgba(247, 252, 255, 0.88)",
      navBorder: "rgba(0, 119, 182, 0.15)",
      navText: "#023e8a",
      navLink: "#4a7a94",
      heroOverlay:
        "linear-gradient(180deg, rgba(202,240,248,0.15) 0%, rgba(2,62,138,0.45) 60%, rgba(2,62,138,0.72) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(0,119,182,0.55) 0%, rgba(2,62,138,0.78) 100%)",
      bodyPattern:
        "radial-gradient(circle at 20% 80%, rgba(144,224,239,0.35) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(202,240,248,0.5) 0%, transparent 45%)",
      sectionRoomsBg: "#f7fcff",
      sectionAmenitiesBg: "#023e8a",
      sectionGalleryBg: "#dff0f7",
      sectionAltBg: "#eaf6fb",
      sectionBookBg: "#0077b6",
      footerBg: "#023e8a",
      footerBorder: "rgba(202, 240, 248, 0.2)",
      btnPrimaryBg: "#0077b6",
      btnPrimaryText: "#ffffff",
      btnPrimaryHover: "#48cae4",
      btnOutlineBorder: "rgba(255, 255, 255, 0.7)",
      btnOutlineText: "#ffffff",
      headingOnSurface: "#023e8a",
      headingOnDark: "#ffffff",
      eyebrowColor: "#0077b6",
    },
    fonts: {
      sans: "var(--font-source-sans)",
      serif: "var(--font-cormorant)",
      headingWeight: "500",
      headingStyle: "italic",
      headingTransform: "none",
      bodyWeight: "400",
    },
    layout: {
      sectionPaddingY: "5rem",
      sectionPaddingYLg: "6.5rem",
      sectionGap: "2rem",
      containerMax: "76rem",
      heroMinHeight: "92vh",
      navHeight: "4rem",
      cardPadding: "1.5rem",
    },
    buttons: {
      radius: "9999px",
      paddingX: "2rem",
      paddingY: "0.85rem",
      tracking: "0.1em",
      fontSize: "0.75rem",
      borderWidth: "2px",
      shadow: "0 4px 14px rgba(0, 119, 182, 0.25)",
      primaryStyle: "gradient",
    },
    cards: {
      radius: "1.25rem",
      borderWidth: "1px",
      border: "1px solid rgba(0, 119, 182, 0.1)",
      shadow: "0 8px 30px rgba(0, 119, 182, 0.08)",
      shadowHover: "0 16px 40px rgba(0, 119, 182, 0.15)",
      imageRadius: "1rem",
    },
    images: {
      filter: "saturate(1.15) brightness(1.05) hue-rotate(-5deg)",
      hoverFilter: "saturate(1.25) brightness(1.08)",
      overlayBlend: "normal",
    },
    navigation: {
      style: "light-glass",
      blur: "16px",
      logoTracking: "0.15em",
      linkTracking: "0.05em",
      borderBottom: true,
    },
    headings: {
      tracking: "0.02em",
      leading: "1.2",
      h1Size: "clamp(3rem, 7vw, 6rem)",
      h2Size: "clamp(2.25rem, 4.5vw, 3.5rem)",
      eyebrowTracking: "0.2em",
    },
  },

  rustic: {
    name: "rustic",
    label: "Rustic",
    colors: {
      background: "#f0e6d8",
      foreground: "#2a2118",
      accent: "#8b4513",
      accentLight: "#c67b3c",
      accentMuted: "#a67c52",
      surface: "#e6d9c8",
      surfaceAlt: "#dbc9b3",
      surfaceDark: "#3d2e1f",
      card: "#faf6f0",
      cardBorder: "#c4a882",
      muted: "#6b5744",
      mutedOnDark: "#d4c4a8",
      mutedSubtle: "#8a7560",
      mutedBorder: "#d4c4a8",
      navBackground: "rgba(61, 46, 31, 0.97)",
      navBorder: "rgba(196, 168, 130, 0.4)",
      navText: "#faf6f0",
      navLink: "#d4c4a8",
      heroOverlay:
        "linear-gradient(180deg, rgba(61,46,31,0.35) 0%, rgba(42,33,24,0.7) 50%, rgba(42,33,24,0.88) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(61,46,31,0.7) 0%, rgba(42,33,24,0.85) 100%)",
      bodyPattern:
        "repeating-linear-gradient(90deg, transparent, transparent 48px, rgba(139,69,19,0.03) 48px, rgba(139,69,19,0.03) 49px)",
      sectionRoomsBg: "#e6d9c8",
      sectionAmenitiesBg: "#3d2e1f",
      sectionGalleryBg: "#dbc9b3",
      sectionAltBg: "#e0d2bf",
      sectionBookBg: "#3d2e1f",
      footerBg: "#2a2118",
      footerBorder: "rgba(196, 168, 130, 0.3)",
      btnPrimaryBg: "#8b4513",
      btnPrimaryText: "#faf6f0",
      btnPrimaryHover: "#a0522d",
      btnOutlineBorder: "rgba(250, 246, 240, 0.5)",
      btnOutlineText: "#faf6f0",
      headingOnSurface: "#2a2118",
      headingOnDark: "#faf6f0",
      eyebrowColor: "#8b4513",
    },
    fonts: {
      sans: "var(--font-nunito-sans)",
      serif: "var(--font-libre-baskerville)",
      headingWeight: "700",
      headingStyle: "normal",
      headingTransform: "none",
      bodyWeight: "400",
    },
    layout: {
      sectionPaddingY: "6rem",
      sectionPaddingYLg: "7.5rem",
      sectionGap: "2.25rem",
      containerMax: "78rem",
      heroMinHeight: "95vh",
      navHeight: "4.25rem",
      cardPadding: "1.625rem",
    },
    buttons: {
      radius: "0.375rem",
      paddingX: "1.75rem",
      paddingY: "0.8rem",
      tracking: "0.14em",
      fontSize: "0.72rem",
      borderWidth: "2px",
      shadow: "0 2px 6px rgba(42, 33, 24, 0.15)",
      primaryStyle: "solid",
    },
    cards: {
      radius: "0.5rem",
      borderWidth: "2px",
      border: "2px solid #c4a882",
      shadow: "0 4px 12px rgba(42, 33, 24, 0.1)",
      shadowHover: "0 8px 24px rgba(42, 33, 24, 0.18)",
      imageRadius: "0.375rem",
    },
    images: {
      filter: "sepia(0.2) saturate(1.1) brightness(0.98)",
      hoverFilter: "sepia(0.12) saturate(1.15) brightness(1.02)",
      overlayBlend: "normal",
    },
    navigation: {
      style: "warm-solid",
      blur: "0px",
      logoTracking: "0.08em",
      linkTracking: "0.04em",
      borderBottom: true,
    },
    headings: {
      tracking: "0.01em",
      leading: "1.25",
      h1Size: "clamp(2.5rem, 5.5vw, 4.5rem)",
      h2Size: "clamp(1.875rem, 3.5vw, 3rem)",
      eyebrowTracking: "0.18em",
    },
  },

  modern: {
    name: "modern",
    label: "Modern",
    colors: {
      background: "#ffffff",
      foreground: "#09090b",
      accent: "#09090b",
      accentLight: "#3f3f46",
      accentMuted: "#71717a",
      surface: "#f4f4f5",
      surfaceAlt: "#e4e4e7",
      surfaceDark: "#09090b",
      card: "#ffffff",
      cardBorder: "#09090b",
      muted: "#52525b",
      mutedOnDark: "#a1a1aa",
      mutedSubtle: "#71717a",
      mutedBorder: "#e4e4e7",
      navBackground: "#ffffff",
      navBorder: "#09090b",
      navText: "#09090b",
      navLink: "#52525b",
      heroOverlay:
        "linear-gradient(180deg, rgba(255,255,255,0.1) 0%, rgba(9,9,11,0.55) 50%, rgba(9,9,11,0.85) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(9,9,11,0.8) 0%, rgba(9,9,11,0.92) 100%)",
      bodyPattern: "none",
      sectionRoomsBg: "#f4f4f5",
      sectionAmenitiesBg: "#09090b",
      sectionGalleryBg: "#ffffff",
      sectionAltBg: "#fafafa",
      sectionBookBg: "#09090b",
      footerBg: "#09090b",
      footerBorder: "#27272a",
      btnPrimaryBg: "#09090b",
      btnPrimaryText: "#ffffff",
      btnPrimaryHover: "#3f3f46",
      btnOutlineBorder: "#ffffff",
      btnOutlineText: "#ffffff",
      headingOnSurface: "#09090b",
      headingOnDark: "#ffffff",
      eyebrowColor: "#52525b",
    },
    fonts: {
      sans: "var(--font-dm-sans)",
      serif: "var(--font-dm-serif)",
      headingWeight: "400",
      headingStyle: "normal",
      headingTransform: "none",
      bodyWeight: "400",
    },
    layout: {
      sectionPaddingY: "4rem",
      sectionPaddingYLg: "5rem",
      sectionGap: "1.5rem",
      containerMax: "72rem",
      heroMinHeight: "88vh",
      navHeight: "3.75rem",
      cardPadding: "1.25rem",
    },
    buttons: {
      radius: "2px",
      paddingX: "1.5rem",
      paddingY: "0.75rem",
      tracking: "0.06em",
      fontSize: "0.75rem",
      borderWidth: "1px",
      shadow: "none",
      primaryStyle: "solid",
    },
    cards: {
      radius: "2px",
      borderWidth: "1px",
      border: "1px solid #09090b",
      shadow: "none",
      shadowHover: "4px 4px 0 #09090b",
      imageRadius: "0px",
    },
    images: {
      filter: "grayscale(0.4) contrast(1.1)",
      hoverFilter: "grayscale(0) contrast(1.05)",
      overlayBlend: "normal",
    },
    navigation: {
      style: "minimal-light",
      blur: "0px",
      logoTracking: "0.02em",
      linkTracking: "0",
      borderBottom: true,
    },
    headings: {
      tracking: "-0.03em",
      leading: "1.1",
      h1Size: "clamp(2.75rem, 8vw, 5rem)",
      h2Size: "clamp(1.75rem, 4vw, 2.75rem)",
      eyebrowTracking: "0.15em",
    },
  },

  "roadside-motel": {
    name: "roadside-motel",
    label: "Roadside Motel",
    colors: {
      background: "#fff8f0",
      foreground: "#1a1a2e",
      accent: "#e63946",
      accentLight: "#ff6b6b",
      accentMuted: "#f4a261",
      surface: "#ffe8d6",
      surfaceAlt: "#ffdab9",
      surfaceDark: "#1a1a2e",
      card: "#ffffff",
      cardBorder: "#457b9d",
      muted: "#5c6b7a",
      mutedOnDark: "#caf0f8",
      mutedSubtle: "#8d99ae",
      mutedBorder: "#bde0fe",
      navBackground: "rgba(26, 26, 46, 0.95)",
      navBorder: "#e63946",
      navText: "#ffffff",
      navLink: "#caf0f8",
      heroOverlay:
        "linear-gradient(135deg, rgba(230,57,70,0.35) 0%, rgba(26,26,46,0.8) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(230,57,70,0.5) 0%, rgba(26,26,46,0.85) 100%)",
      bodyPattern: "none",
      sectionRoomsBg: "#ffe8d6",
      sectionAmenitiesBg: "#1a1a2e",
      sectionGalleryBg: "#fff8f0",
      sectionAltBg: "#ffdab9",
      sectionBookBg: "#1a1a2e",
      footerBg: "#14213d",
      footerBorder: "#e63946",
      btnPrimaryBg: "#e63946",
      btnPrimaryText: "#ffffff",
      btnPrimaryHover: "#ff6b6b",
      btnOutlineBorder: "#ffffff",
      btnOutlineText: "#ffffff",
      headingOnSurface: "#1a1a2e",
      headingOnDark: "#ffffff",
      eyebrowColor: "#e63946",
    },
    fonts: {
      sans: "var(--font-nunito-sans)",
      serif: "var(--font-libre-baskerville)",
      headingWeight: "700",
      headingStyle: "normal",
      headingTransform: "uppercase",
      bodyWeight: "400",
    },
    layout: {
      sectionPaddingY: "4.5rem",
      sectionPaddingYLg: "5.5rem",
      sectionGap: "1.75rem",
      containerMax: "76rem",
      heroMinHeight: "85vh",
      navHeight: "4rem",
      cardPadding: "1.25rem",
    },
    buttons: {
      radius: "9999px",
      paddingX: "1.75rem",
      paddingY: "0.8rem",
      tracking: "0.12em",
      fontSize: "0.75rem",
      borderWidth: "2px",
      shadow: "0 4px 0 #14213d",
      primaryStyle: "solid",
    },
    cards: {
      radius: "12px",
      borderWidth: "2px",
      border: "2px solid #457b9d",
      shadow: "4px 4px 0 #1a1a2e",
      shadowHover: "6px 6px 0 #e63946",
      imageRadius: "8px",
    },
    images: {
      filter: "saturate(1.3) contrast(1.1)",
      hoverFilter: "saturate(1.4) contrast(1.15)",
      overlayBlend: "normal",
    },
    navigation: {
      style: "retro",
      blur: "0px",
      logoTracking: "0.2em",
      linkTracking: "0.08em",
      borderBottom: true,
    },
    headings: {
      tracking: "0.05em",
      leading: "1.2",
      h1Size: "clamp(2.5rem, 6vw, 4.5rem)",
      h2Size: "clamp(1.75rem, 3.5vw, 2.75rem)",
      eyebrowTracking: "0.25em",
    },
  },

  "business-hotel": {
    name: "business-hotel",
    label: "Business Hotel",
    colors: {
      background: "#f8fafc",
      foreground: "#0f172a",
      accent: "#1e40af",
      accentLight: "#3b82f6",
      accentMuted: "#64748b",
      surface: "#f1f5f9",
      surfaceAlt: "#e2e8f0",
      surfaceDark: "#0f172a",
      card: "#ffffff",
      cardBorder: "#cbd5e1",
      muted: "#64748b",
      mutedOnDark: "#94a3b8",
      mutedSubtle: "#94a3b8",
      mutedBorder: "#e2e8f0",
      navBackground: "#ffffff",
      navBorder: "#1e40af",
      navText: "#0f172a",
      navLink: "#64748b",
      heroOverlay:
        "linear-gradient(180deg, rgba(15,23,42,0.3) 0%, rgba(15,23,42,0.75) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(30,64,175,0.6) 0%, rgba(15,23,42,0.85) 100%)",
      bodyPattern: "none",
      sectionRoomsBg: "#f1f5f9",
      sectionAmenitiesBg: "#0f172a",
      sectionGalleryBg: "#ffffff",
      sectionAltBg: "#f8fafc",
      sectionBookBg: "#1e3a8a",
      footerBg: "#0f172a",
      footerBorder: "#1e40af",
      btnPrimaryBg: "#1e40af",
      btnPrimaryText: "#ffffff",
      btnPrimaryHover: "#3b82f6",
      btnOutlineBorder: "#ffffff",
      btnOutlineText: "#ffffff",
      headingOnSurface: "#0f172a",
      headingOnDark: "#ffffff",
      eyebrowColor: "#1e40af",
    },
    fonts: {
      sans: "var(--font-source-sans)",
      serif: "var(--font-dm-serif)",
      headingWeight: "600",
      headingStyle: "normal",
      headingTransform: "none",
      bodyWeight: "400",
    },
    layout: {
      sectionPaddingY: "4rem",
      sectionPaddingYLg: "5rem",
      sectionGap: "1.5rem",
      containerMax: "72rem",
      heroMinHeight: "80vh",
      navHeight: "3.5rem",
      cardPadding: "1.25rem",
    },
    buttons: {
      radius: "4px",
      paddingX: "1.5rem",
      paddingY: "0.7rem",
      tracking: "0.05em",
      fontSize: "0.8rem",
      borderWidth: "1px",
      shadow: "none",
      primaryStyle: "solid",
    },
    cards: {
      radius: "6px",
      borderWidth: "1px",
      border: "1px solid #cbd5e1",
      shadow: "0 1px 3px rgba(15,23,42,0.08)",
      shadowHover: "0 4px 12px rgba(15,23,42,0.12)",
      imageRadius: "4px",
    },
    images: {
      filter: "saturate(0.95) brightness(1.02)",
      hoverFilter: "saturate(1) brightness(1.05)",
      overlayBlend: "normal",
    },
    navigation: {
      style: "corporate",
      blur: "8px",
      logoTracking: "0.04em",
      linkTracking: "0.02em",
      borderBottom: true,
    },
    headings: {
      tracking: "-0.01em",
      leading: "1.2",
      h1Size: "clamp(2.25rem, 5vw, 3.5rem)",
      h2Size: "clamp(1.5rem, 3vw, 2.25rem)",
      eyebrowTracking: "0.12em",
    },
  },

  "historic-inn": {
    name: "historic-inn",
    label: "Historic Inn",
    colors: {
      background: "#faf6f0",
      foreground: "#2c1810",
      accent: "#722f37",
      accentLight: "#a44a55",
      accentMuted: "#8b6914",
      surface: "#f0e8dc",
      surfaceAlt: "#e8dfd0",
      surfaceDark: "#2c1810",
      card: "#fffdf8",
      cardBorder: "#c4a882",
      muted: "#6b5344",
      mutedOnDark: "#d4c4a8",
      mutedSubtle: "#8a7560",
      mutedBorder: "#e0d2bf",
      navBackground: "rgba(44, 24, 16, 0.96)",
      navBorder: "rgba(196, 168, 130, 0.5)",
      navText: "#faf6f0",
      navLink: "#d4c4a8",
      heroOverlay:
        "linear-gradient(180deg, rgba(44,24,16,0.4) 0%, rgba(44,24,16,0.85) 100%)",
      ctaOverlay:
        "linear-gradient(135deg, rgba(114,47,55,0.55) 0%, rgba(44,24,16,0.88) 100%)",
      bodyPattern:
        "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(114,47,55,0.02) 2px, rgba(114,47,55,0.02) 4px)",
      sectionRoomsBg: "#f0e8dc",
      sectionAmenitiesBg: "#2c1810",
      sectionGalleryBg: "#faf6f0",
      sectionAltBg: "#e8dfd0",
      sectionBookBg: "#722f37",
      footerBg: "#2c1810",
      footerBorder: "rgba(196, 168, 130, 0.35)",
      btnPrimaryBg: "#722f37",
      btnPrimaryText: "#faf6f0",
      btnPrimaryHover: "#a44a55",
      btnOutlineBorder: "rgba(250, 246, 240, 0.6)",
      btnOutlineText: "#faf6f0",
      headingOnSurface: "#2c1810",
      headingOnDark: "#faf6f0",
      eyebrowColor: "#722f37",
    },
    fonts: {
      sans: "var(--font-lato)",
      serif: "var(--font-playfair)",
      headingWeight: "400",
      headingStyle: "italic",
      headingTransform: "none",
      bodyWeight: "400",
    },
    layout: {
      sectionPaddingY: "6rem",
      sectionPaddingYLg: "7.5rem",
      sectionGap: "2rem",
      containerMax: "78rem",
      heroMinHeight: "92vh",
      navHeight: "4.25rem",
      cardPadding: "1.75rem",
    },
    buttons: {
      radius: "2px",
      paddingX: "2rem",
      paddingY: "0.85rem",
      tracking: "0.14em",
      fontSize: "0.72rem",
      borderWidth: "1px",
      shadow: "none",
      primaryStyle: "solid",
    },
    cards: {
      radius: "2px",
      borderWidth: "1px",
      border: "1px solid #c4a882",
      shadow: "0 2px 8px rgba(44, 24, 16, 0.08)",
      shadowHover: "0 8px 24px rgba(44, 24, 16, 0.14)",
      imageRadius: "0px",
    },
    images: {
      filter: "sepia(0.15) saturate(1.05)",
      hoverFilter: "sepia(0.08) saturate(1.1)",
      overlayBlend: "normal",
    },
    navigation: {
      style: "historic",
      blur: "0px",
      logoTracking: "0.12em",
      linkTracking: "0.06em",
      borderBottom: true,
    },
    headings: {
      tracking: "0.02em",
      leading: "1.25",
      h1Size: "clamp(2.75rem, 5.5vw, 4.75rem)",
      h2Size: "clamp(2rem, 3.5vw, 3rem)",
      eyebrowTracking: "0.22em",
    },
  },
} as const;

export type ThemeName = keyof typeof themes;
export type Theme = (typeof themes)[ThemeName];

export const themeNames = Object.keys(themes) as ThemeName[];

export function isThemeName(value: string): value is ThemeName {
  return value in themes;
}

export function getTheme(theme: string): Theme {
  if (isThemeName(theme)) {
    return themes[theme];
  }
  return themes.luxury;
}

/** CSS custom properties for one theme. */
export function themeToCssVariables(themeName: string): Record<string, string> {
  const t = getTheme(themeName);
  const c = t.colors;
  return {
    "--background": c.background,
    "--foreground": c.foreground,
    "--accent": c.accent,
    "--accent-light": c.accentLight,
    "--accent-muted": c.accentMuted,
    "--surface": c.surface,
    "--surface-alt": c.surfaceAlt,
    "--surface-dark": c.surfaceDark,
    "--card": c.card,
    "--card-border": c.cardBorder,
    "--muted": c.muted,
    "--muted-on-dark": c.mutedOnDark,
    "--muted-subtle": c.mutedSubtle,
    "--muted-border": c.mutedBorder,
    "--nav-background": c.navBackground,
    "--nav-border": c.navBorder,
    "--nav-text": c.navText,
    "--nav-link": c.navLink,
    "--hero-overlay": c.heroOverlay,
    "--cta-overlay": c.ctaOverlay,
    "--body-pattern": c.bodyPattern,
    "--section-rooms-bg": c.sectionRoomsBg,
    "--section-amenities-bg": c.sectionAmenitiesBg,
    "--section-gallery-bg": c.sectionGalleryBg,
    "--section-alt-bg": c.sectionAltBg,
    "--section-book-bg": c.sectionBookBg,
    "--footer-bg": c.footerBg,
    "--footer-border": c.footerBorder,
    "--btn-primary-bg": c.btnPrimaryBg,
    "--btn-primary-text": c.btnPrimaryText,
    "--btn-primary-hover": c.btnPrimaryHover,
    "--btn-outline-border": c.btnOutlineBorder,
    "--btn-outline-text": c.btnOutlineText,
    "--heading-on-surface": c.headingOnSurface,
    "--heading-on-dark": c.headingOnDark,
    "--eyebrow-color": c.eyebrowColor,
    "--theme-font-sans": t.fonts.sans,
    "--theme-font-serif": t.fonts.serif,
    "--font-heading-weight": t.fonts.headingWeight,
    "--font-heading-style": t.fonts.headingStyle,
    "--font-heading-transform": t.fonts.headingTransform,
    "--font-body-weight": t.fonts.bodyWeight,
    "--section-padding-y": t.layout.sectionPaddingY,
    "--section-padding-y-lg": t.layout.sectionPaddingYLg,
    "--section-gap": t.layout.sectionGap,
    "--container-max": t.layout.containerMax,
    "--hero-min-height": t.layout.heroMinHeight,
    "--nav-height": t.layout.navHeight,
    "--card-padding": t.layout.cardPadding,
    "--button-radius": t.buttons.radius,
    "--button-padding-x": t.buttons.paddingX,
    "--button-padding-y": t.buttons.paddingY,
    "--button-tracking": t.buttons.tracking,
    "--button-font-size": t.buttons.fontSize,
    "--button-border-width": t.buttons.borderWidth,
    "--button-shadow": t.buttons.shadow,
    "--card-radius": t.cards.radius,
    "--card-border-width": t.cards.borderWidth,
    "--card-shadow": t.cards.shadow,
    "--card-shadow-hover": t.cards.shadowHover,
    "--image-radius": t.cards.imageRadius,
    "--image-filter": t.images.filter,
    "--image-filter-hover": t.images.hoverFilter,
    "--heading-tracking": t.headings.tracking,
    "--heading-leading": t.headings.leading,
    "--h1-size": t.headings.h1Size,
    "--h2-size": t.headings.h2Size,
    "--eyebrow-tracking": t.headings.eyebrowTracking,
    "--nav-blur": t.navigation.blur,
    "--nav-logo-tracking": t.navigation.logoTracking,
    "--nav-link-tracking": t.navigation.linkTracking,
  };
}

/**
 * Generates a <style> block with CSS variables for every theme.
 * Applied via html[data-theme="…"] so switching hotel.config.ts theme works
 * without relying on inline styles (which Next.js may strip from <html>).
 */
export function generateThemeStylesheet(): string {
  return themeNames
    .map((name) => {
      const vars = themeToCssVariables(name);
      const block = Object.entries(vars)
        .map(([key, value]) => `  ${key}: ${value};`)
        .join("\n");
      return `html[data-theme="${name}"] {\n${block}\n}`;
    })
    .join("\n\n");
}

/** @deprecated Use getTheme() */
export function getThemeTokens(theme: string): Theme {
  return getTheme(theme);
}

/** @deprecated Use themes directly */
export const themeTokens = themes;
